kind: pipeline
name: default
steps:
- name: build
  image: node:18
  commands:
  - sh ./.drone/build.sh
- name: publish
  image: plugins/docker
  settings:
    repo: wunduniik/node-microservice
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
- name: deploy
  image: docker
  commands:
  - sh ./.drone/deploy.sh
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  privileged: true  
volumes:
- name: dockersock
  path: /var/run/docker.sock
