kind: pipeline
type: docker
name: default

steps:
- name: build
  image: node:18
  commands:
  - sh ./.drone/build.sh

- name: publish
  image: plugins/docker
  settings:
    repo: wunduniik/node-microservice
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: deploy
  image: docker:20.10
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - sh ./.drone/deploy.sh

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
